### PR TITLE
🚧Remove deno scripts and config

### LINKED ISSUE #1042: 🚧Remove deno scripts and config
### Complete The Item Below

- [x] I have updated the title without removing the 🚧 emoji.

### Description

Remove all deno scripts and related configuration.

Do the following:
1. Delete the _**deno.json**_ file
2. Delete the _**deno.lock**_ file
3. Delete the _**.github/cicd**_ directory and all of its contents

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after the PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] Deleted the _**deno.json**_ file
- [x] Deleted the _**deno.lock**_ file
- [x] Deleted the _**.github/cicd**_ directory and all of its contents
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Issue Dependencies

_No response_

### Related Work

_No response_

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### PR DESCRIPTION
**Pull request by bmonish**
### **Description:**

To allow this pull request to be merged, please make sure that the following items of this pull request are complete.

This pull request closes #1042

✅The pull request head branch must be a feature branch with the syntax 'feature/<issue-num>-sync-testing'.  
✅The pull request base branch must be a 'main' or 'preview' branch..  
✅The pull request head branch contains a valid issue number.  
✅The pull request title matches the linked issue title exactly.  
✅The pull request assignees match the assignees of the issue.  
✅The pull request labels match the labels of the issue.  
✅The pull request organizational projects match the organizational projects of the issue.  
✅The pull requests milestone matches the milestone of the issue.  

---

### **Additional Info:**
1. Pull requests are automatically synced with the associated issue upon creation by one of the KinsonDigital workflow bots. 
2. The associated issue is the issue number that is embedded in the pull request head branch.
3. The list above will be automatically updated as the pull request's various settings match or do not match the associated issue.
4. To manually sync the pull request to the issue, create a comment with the `[run-sync]` command.
> [!Note] You must be an admin member of the organization to use this command.

---

- [x] Sync with the issue.  Use this to enable or disable this pull request from syncing with its associated issue.

### CODE REVIEW

**Comment by bmonish** [comment]
@CalvinWilkinson Can you please explain how I can run the tests locally?

**Comment by KinsonDigitalAdmin** [comment]
> @CalvinWilkinson Can you please explain how I can run the tests locally?

Sure thing.  Which IDE are you using?

> [!Note]
> The unit tests have passed. The unit test status check results for this pull request show this. 
> image

I would be happy to help you learn how to run those tests. There are many ways to run tests, but it depends on what tools you are using and your experience, which is why I ask about what IDE you are using.

**Comment by KinsonDigitalAdmin** [comment]
@bmonish 

Just a quick tip.  You do not have to use the issue number in the git commit messages.  😊

It's fine to use all lowercase and [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). I do not try to force outside contributors to use conventional commits, but it seems like you are going that route,, so I thought you would be interested.

**Comment by KinsonDigitalAdmin** [comment]
@bmonish 

Just a quick note.  I have made a couple of commits on your branch on my behalf so I can introduce a workflow change as well as force the status checks to be executed.

**Review by KinsonDigitalAdmin — APPROVED** [review]

**Pull request merged**
