### PR TITLE
🚧Refactor WindowSizeEventArgs ctor param data types 

### PR DESCRIPTION
**Pull request by SyedMSawaid**
<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_preview feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/feature/<issue-num>-<description>
      Example: preview/feature/123-my-preview-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_preview release_** branch, with the correct naming syntax, in the following example:
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
    Example: preview/v1.2.3-preview.4
    ```
  </details>

- [ ] The **_base(target)_** branch for this pull request is a **_preview release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

💡For more information on branching, refer to the project's [branching documentation](../../Documentation/Branching.md).

- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] Pull request title matches the title of the associated issue.

- [ ] A `preview` label has been added to the pull request.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] Project assigned matches the project of the associated issue.

- [ ] Milestone assigned matches the milestone of the associated issue.

- [ ] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's discuss it.

- [ ] I have manually tested my code changes to the best of my ability.

- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

### CODE REVIEW

**Comment by SyedMSawaid** [comment]
@CalvinWilkinson I followed the steps as you mentioned in the last PR. I hope this one satisfy all the requirements.

**Comment by CalvinWilkinson** [comment]
> @CalvinWilkinson I followed the steps you mentioned in the last PR. I hope this one satisfies all the requirements.

@SyedMSawaid . Thanks for recreating the PR. Unfortunately, the branch name is still incorrect.

The branch names must always be all lower case and words are separated by hyphens, not underscores.

**Here is the syntax of a preview feature branch:**
- Syntax: preview/feature/<issue-num>-<short-description>
- Example: preview/feature/171-refactor-ctor-params

So the previous PR that you closed had the branch below:
image

The hyphens for this one are correct but there are upper-case letters.

The branch for this one which is at the top of the page is below:
image

This one has uppercase letters and underscores.

---

I will apologize for this because I did not mention the lowercase requirement of the branch name.  I went back to look in the [Branching Documentation](https://github.com/KinsonDigital/Velaptor/blob/release/v1.0.0/Documentation/Branching.md) as well and noticed that though it does show examples of the branch names, it does not explicitly say that they all have to be lowercase.

I take full blame for this of course.  I would make an exception but the CICD system will reject it.  Could you please recreate the PR with the correct branch again?  😟

**Quick Note:**
You also absolutely do not have to make the branch description the same text as the issue title.  Short and simple is ideal.  The issue number is the branch name is there for people to go to the issue for more detail if need be.  But there is nothing _**wrong**_ with a longer branch name and it will not get rejected.  This is just a quick tip is all.

If you want to use the example below as the branch name, this would be great.

**Branch Name:** preview/feature/171-refactor-ctor-params

**Comment by CalvinWilkinson** [comment]
@SyedMSawaid 
Just a quick positive note.   With the increased influx of outside contributions, this has been surfacing issues and details that need to be addressed with the outside contribution process.

So you are bringing value to the project!!  Don't sweat it.  I greatly appreciate this because I am improving the contribution docs and process as a direct result of you taking the time to contribute!!

This is exactly what open source is about.  Great job!!  🤘🏼

**Comment by SyedMSawaid** [comment]
What doesn't kill me, makes me strong. 😅

It is okay. I will create a new one. I think once I get into the habit of it, it will be fine.

The problem I have is shortage of time so I hope it is okay on your end that I am a bit slow to adapt to the OSS system.

**Pull request closed without merging**
