### PR TITLE
🚧Increase spacing between buttons on rect scene

### PR DESCRIPTION
**Pull request by quinnrdavis**
<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>

- [x] The **_head(source)_** branch for this pull request is a **_preview feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/feature/<issue-num>-<description>
      Example: preview/feature/123-my-preview-feature
      ```
    </details>

- [x] The **_head(source)_** branch for this pull request is created from a **_preview release_** branch, with the correct naming syntax, in the following example:
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
    Example: preview/v1.2.3-preview.4
    ```
  </details>

- [x] The **_base(target)_** branch for this pull request is a **_preview release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

💡For more information on branching, refer to the project's [branching documentation](../../Documentation/Branching.md).

- [x] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [x] Pull request title matches the title of the associated issue.

- [x] A `preview` label has been added to the pull request.

- [x] The labels attached to this PR match the labels attached to the associated issue.

- [x] Project assigned matches the project of the associated issue.

- [x] Milestone assigned matches the milestone of the associated issue.

- [x] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's discuss it.

- [x] I have manually tested my code changes to the best of my ability.

- [x] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

### CODE REVIEW

**Comment by CalvinWilkinson** [comment]
@quinnrdavis 
Please remove the piece of text from the end of the title.
You must have accidentally grabbed the webpage issue number on the page.
image

**Comment by CalvinWilkinson** [comment]
> @quinnrdavis Please remove the piece of text from the end of the title. You must have accidentally grabbed the webpage issue number on the page. image

Thanks!!

**Comment by CalvinWilkinson** [comment]
@quinnrdavis I was just wanting to check in and see if you have made any progress on this.
Please let me know.  If the issue goes too long then the system will flag it as stale.  I could of course take it out of stale status but I was hoping to get some progress on this so we can release it.

Cheers!!

**Comment by quinnrdavis** [comment]
Oh yeah I finished it that first day, it should be ready to go.

**Comment by CalvinWilkinson** [comment]
> Oh yeah I finished it that first day, it should be ready to go.

Ah ok.  Awesome!!

If you don't mind, next time can you please @ mention me with a comment to let me know that it is ready for review?  This way the GitHub notification system will show that there is activity and I can see that it is ready. :)

I am getting ready to do a release so I will have this out this release.

**Review by CalvinWilkinson — APPROVED** [review]

**Pull request merged**
