### PR TITLE
update NVorbis from 0.10.4 to 0.10.5 and others

### LINKED ISSUE #389: 🚧Update NVorbis NuGet package
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the **NVorbis** NuGet package from version _**v0.10.3**_ to **_v0.10.5+_**.

If the version of the package is greater than _**v0.10.5**_, only update the package if it is a minor or path update.

**History:**
This update was intended in issue #293, but somehow it got downgraded from version _**v0.10.4**_ to version _**v0.10.3**_.  The intention was researched but no answer could be found and the intention or reasoning for the downgrade is unclear.

You can view the downgrade change [here](https://github.com/KinsonDigital/Velaptor/pull/337/files).  Look at the _**Velaptor.csproj**_ file for the change.  

If there is a major update available when this issue is being worked on, please notify @CalvinWilkinson about the higher package update available before updating the package.

### Acceptance Criteria

- [x] ~**NVorbis** NuGet package updated from version _**v0.10.3**_ to version _**v0.10.5+**_~
- [x] Remove the commented package reference for **NVorbis** that is set for version _**v0.10.5**_

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

_No response_

### Related Work

_No response_

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### PR DESCRIPTION
**Pull request by x0rld**
resolve #389

### CODE REVIEW

**Comment by x0rld** [comment]
@CalvinWilkinson if you want to see the dependencies update

**Comment by CalvinWilkinson** [comment]
@x0rld 

If you could, can you please do the following:

1. Recreate the pull request:
   - The PR head(source) branch must be renamed.  The project depends on branch naming rules for its CICD and status checks.
   - The PR base(destination) branch must be the latest preview branch.  Currently the latest preview branch is _**preview/v1.0.0-preview.11**_.
   - The PR title must have the **EXACT** same title as the related issue.
   - The PR must use a PR template for preview feature branches.
     - [Preview Feature PR Template](https://github.com/KinsonDigital/.github/blob/master/.github/PULL_REQUEST_TEMPLATE/preview-feature-pr-template.md)
   - The PR must be in draft
   - We use [Early Pull Requests](https://carlosperez.medium.com/pull-request-first-f6bb667a9b6)

Currently, we are in preview.  This means that the branch needs to be a **_preview feature branch_**.  The naming syntax for a **_preview feature branch_** is 👉🏼 _**preview/feature/<issue-num>-<description>**_
**Example:** preview/feature/123-my-branch

So since the issue number for this PR is 389, this means the branch should be named something like the example below:
    **preview/feature/389-update-nvorbis**

Once these things are done, I will recheck everything and we should be good to go.  If you have a question, don't hesitate to reach out.  :)

---

### **Here are some resources on how to contribute:**
1. [Project README](https://github.com/KinsonDigital/Velaptor/blob/release/v1.0.0/README.md)
    - Scroll down to the **🙏🏼 Contributing** section.
3. [Branching Docs](https://github.com/KinsonDigital/Velaptor/blob/release/v1.0.0/Documentation/Branching.md)

**Comment by CalvinWilkinson** [comment]
@x0rld I was just check-in.  Is there any intention of moving forward with this?
I noticed that it has been 5 days since the last change with the PR.

If so, let me know if you need anything else.

You can also reach me with any questions on the [discord server](https://discord.gg/qewu6fNgv7).

Cheers!!

**Comment by CalvinWilkinson** [comment]
PR closed without merging.

The PR does not meet contribution standards and guidelines.  No response on the status of the PR either.

PR will be recreated and then implemented by @CalvinWilkinson

**Pull request closed without merging**
